"""empty message

Revision ID: 4b880a1d62c9
Revises: c472eb075b6a
Create Date: 2019-12-15 18:51:52.242497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b880a1d62c9'
down_revision = 'c472eb075b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_test_plan', sa.Column('status', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_test_plan', 'status')
    # ### end Alembic commands ###
