""" update model

Revision ID: c472eb075b6a
Revises: 8bdc86a39d57
Create Date: 2019-12-08 13:16:22.677634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c472eb075b6a'
down_revision = '8bdc86a39d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='tb_user')
    op.create_unique_constraint(None, 'tb_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_user', type_='unique')
    op.create_index('name', 'tb_user', ['name'], unique=True)
    # ### end Alembic commands ###
